version: "3.9"
services:
  traefik:
    image: "traefik:v2.5"
    container_name: "sq_traefik"
    command:
      - "--api.insecure=true"
      - "--providers.file=true"
      - "--providers.file.filename=/config/traefik.yml"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.proxyProtocol.insecure"
      - "--entryPoints.web.forwardedHeaders.insecure"
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik.yml:/config/traefik.yml
#  nginx:
#    image: "nginx:latest"
#    container_name: "sq_nginx"
#    restart: always
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
  database:
    container_name: sq_mongodb
    image: mongo:6.0
    volumes:
      - ./data:/data/db
  api:
    container_name: sq_api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - type: bind
        source: ./config.js
        target: /sqtracker/config.js
    depends_on:
      - database
  client:
    container_name: sq_client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - type: bind
        source: ./config.js
        target: /sqtracker/config.js
    depends_on:
      - api

